### ISSUE TITLE
0.9.3-rc0 fails to build on Fedora Rawhide.

### ISSUE THREAD

**Issue by rubenk** [sheepdog/sheepdog#117]
Hi
While trying to update the ancient rpms in Fedora to the latest sheepdog version, I bumped into this failure:

```
Built dog
gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -DNDEBUG -ggdb3  	   -Wall -Wshadow -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wpointer-arith -Wwrite-strings -Wbad-function-cast -Wmissing-format-attribute -Wformat=2 -Wformat-security -Wformat-nonliteral -Wno-long-long -Wno-strict-aliasing -Wcast-align  	-D_GNU_SOURCE -D_LGPL_SOURCE -std=gnu99  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -o dog object_tree.o sha1_file.o snap.o trunk.o farm.o slice.o dog.o common.o treeview.o vdi.o node.o cluster.o upgrade.o   ../lib/libsheepdog.a -lpthread -lzookeeper_mt -lrt 
/usr/bin/ld: ../lib/libsheepdog.a(ec_base.o): relocation R_X86_64_32S against `gflog_base' can not be used when making a shared object; recompile with -fPIC
../lib/libsheepdog.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:413: recipe for target 'dog' failed
make[1]: *** [dog] Error 1
make[1]: Leaving directory '/home/ruben/pkg/sheepdog/sheepdog-049816cdb57ccefcc1f253852b72ec7d2b2cc80d/dog'
```

This probably has something to with the build flags Fedora is setting by default (-fPIE), and the fact that lib/libsheepdog is not compiled as a position independent library by libtool:

```
ar cru libsheepdog.a event.o logger.o net.o util.o rbtree.o strbuf.o sha1.o option.o work.o sockfd_cache.o fec.o sd_inode.o sha1_ssse3.o isa-l/bin/ec_base.o isa-l/bin/ec_highlevel_func.o isa-l/bin/ec_multibinary.o isa-l/bin/gf_2vect_dot_prod_sse.o isa-l/bin/gf_3vect_dot_prod_sse.o isa-l/bin/gf_4vect_dot_prod_sse.o isa-l/bin/gf_5vect_dot_prod_sse.o isa-l/bin/gf_6vect_dot_prod_sse.o isa-l/bin/gf_vect_dot_prod_sse.o isa-l/bin/gf_vect_mul_avx.o isa-l/bin/gf_vect_mul_sse.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libsheepdog.a

```

**Comment by rubenk** [comment]
For some reason the isa code wasn't compiled as position independent code.
It turns out this is fixed by 4d18fd20b2dade08b6588db49c977327dd82f249.

Can this patch be picked into the stable 0.9 branch?

**Comment by mitake** [comment]
Hi @rubenk , thanks for your report. I'll pick the patch ASAP.

**Comment by mitake** [comment]
Hi @rubenk , I pushed the commit to stable-0.9. Could you test the branch?

**Comment by rubenk** [comment]
Thanks @mitake. The branch now builds.

There's one issue left:
rpmlint results_sheepdog/0.9.3/0.1.rc0.fc24/sheepdog-0.9.3-0.1.rc0.fc24.x86_64.rpm
sheepdog.x86_64: W: executable-stack /usr/sbin/dog
sheepdog.x86_64: W: executable-stack /usr/sbin/sheep

It seems the objects which are combined into the isa static archive are not marked as having a non-executable stack.  There is code in lib/isa-l/make.inc which does that, but only for a shared library and afaict that isn't used.

Would you like me to open a separate issue for this?

**Comment by mitake** [comment]
@rubenk yes, this is a new issue. Could you one the new one? Thanks a lot for testing!
