### ISSUE TITLE
iSCSI: handle a case of snapshot -> failover

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#124]
Ongoing work: https://github.com/sheepdog/tgt/tree/lock-and-serialize

**Comment by tmenjo** [comment]
@mitake:

I tested your lock-and-serialize branch with the latest Sheepdog (commit [3373df2](https://github.com/sheepdog/sheepdog/tree/3373df269e9ac2d26344296f99bf00e09de67de7)). Yours seems to be old a little, so I rebased yours onto [upstream v1.0.66](https://github.com/fujita/tgt/tree/v1.0.66) before testing. My rebased branch is [here](https://github.com/tmenjo/tgt/tree/lock-and-serialize).

Before and after snapshot and failover, checksum of files on a filesystem on a multipath device are consistent. So it seems to work well!

Tested-by: Takashi Menjo &lt;menjo.takashi@lab.ntt.co.jp&gt;

**Comment by mitake** [comment]
@tmenjo thanks a lot :) I'll send the patches to the tgt ML
