### ISSUE TITLE
refine output of dog vdi lock list

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#126]
It should be like the output of dog vdi list

**Comment by tmenjo** [comment]
@mitake:

I will fix this issue together with another one that `dog node lock unlock` cannot unlock snapshot VDI. How about?

I think refined output of `dog vdi lock list` should be like as below:

```
  Name        Id  VDI id    Tag  Owner node
  foovdi       0  270cf4         IPv4 ip:192.168.122.11 port:7000(shared) IPv4 ip:192.168.122.12 port:7000(shared) IPv4 ip:192.168.122.13 port:7000(shared)
```

cf: Output of `dog vdi list`:

```
  Name        Id    Size    Used  Shared    Creation time   VDI id  Copies  Tag   Block Size Shift
  foovdi       0  1.0 GB  0.0 MB  0.0 MB 2016-09-06 10:39   270cf4      2                22
```

cf: Output of current (v1.0) `dog vdi lock list`:
```
VDI | owner node
foovdi | IPv4 ip:192.168.122.11 port:7000(shared) IPv4 ip:192.168.122.12 port:7000(shared) IPv4 ip:192.168.122.13 port:7000(shared)
```

**Comment by mitake** [comment]
@tmenjo looks good. How about changing the column name `Owner node` to `Owner node(s)`?

**Comment by tmenjo** [comment]
@mitake: Sure. Like this:

```
  Name        Id  VDI id    Tag  Owner node(s)
  foovdi       0  270cf4         IPv4 ip:192.168.122.11 port:7000(shared) IPv4 ip:192.168.122.12 port:7000(shared) IPv4 ip:192.168.122.13 port:7000(shared)
```

**Comment by tmenjo** [comment]
I found that struct vdi_state has neither tag nor snapid and struct sd_inode does not have any lock state. Implementing refined lock list like as above, I think I have to run O(n^2) nested loop for vdi_state and sd_inode...

So I will remove "Id" and "Tag" from refined output. Even after that, "dog vdi lock list" can join with "dog vdi list" on "VDI id".

**Comment by tmenjo** [comment]
@mitake:

I opened PR #307. Please review and comment.

Note that I can find the way listing snapid, tag, and lock state without nested loop. For each sd_inode (that already has snapid and tag), I run binary search of vdi_state to get lock state.
