### ISSUE TITLE
fix discard support

### ISSUE THREAD

**Issue by vtolstov** [sheepdog/sheepdog#127]
In thin provisioning discard support is very useful, to delete unneeded data. In latest sheepdog master discard not working and corrupt fs image.

**Comment by mitake** [comment]
@vtolstov could you provide:
 - qemu command line options (might be generated by libvirt)
 - fstrim command line options
?
It will make my debugging easier.

**Comment by vtolstov** [comment]
```
qemu-system-x86_64 -enable-kvm -name 30675 -S -machine pc-i440fx-1.7,accel=kvm,usb=off -m 1024 -realtime
mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid 6aeec689-f4e9-fe89-12ff-00005009bb50 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/30675.monitor,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device virtio-scsi-pci,id=scsi0,num_queues=1,bus=pci.0,addr=0x4 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6 -drive file=sheepdog:30675,if=none,id=drive-scsi0-0-0-0,format=raw,cache=none,discard=ignore,aio=native -device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=1 -drive if=none,id=drive-scsi0-0-1-0,readonly=on,format=raw -device scsi-cd,bus=scsi0.0,channel=0,scsi-id=1,lun=0,drive=drive-scsi0-0-1-0,id=scsi0-0-1-0 -netdev tap,fd=151,id=hostnet0,vhost=on,vhostfd=152 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:00:42:87,bus=pci.0,addr=0x3,rombar=0 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev socket,id=charchannel0,path=/var/lib/libvirt/qemu/30675.agent,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 -device usb-mouse,id=input0 -device usb-kbd,id=input1 -vnc [::]:0,password -device VGA,id=video0,vgamem_mb=16,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -object rng-random,id=objrng0,filename=/dev/random -device virtio-rng-pci,rng=objrng0,id=rng0,max-bytes=1024,period=2000,bus=pci.0,addr=0x7 -msg timestamp=on
```
fstrim -v /

**Comment by vtolstov** [comment]
most important that we need virtio-scsi controller and virtio-scsi device with discard=unmap

**Comment by mitake** [comment]
Thanks!

**Comment by mitake** [comment]
@vtolstov I refined discard support. You can find the code here: https://github.com/sheepdog/qemu/tree/discard

Could you test it?

**Comment by vtolstov** [comment]
@mitake i'm create new qemu package, but forget to add some patches that goes after 2.4.0 release, please wait some time, i'm pick needed patches and build 2.4.0 qemu to test.
Does df -h inside vm needs to output used space equal to dog vdi list disk usage?
Before this patch dog vdi list displays disk usage equals dog vdi list * 2

**Comment by vtolstov** [comment]
I'm test and all works fine, no errors reported in sheep debug log.
I'm test on 5Gb vm with 5Gb usage size, after removing files inside vm i have 909M 
in dog vdi list i have 1.6.

**Comment by mitake** [comment]
@vtolstov Thanks a lot for testing, could you add your Tested-by tag on QEMU mailing list?

**Comment by vtolstov** [comment]
Ok
