### ISSUE TITLE
Documentation for Sheepdog wire protocol

### ISSUE THREAD

**Issue by neurodrone** [sheepdog/sheepdog#153]
Is it important to understand how the messaging takes place between the clients and the gateway in order to create truly portable and multi-lingual clients (that are independent of the C shared libraries underneath).

This helps improve robustness for such clients since (a) we can write internal unit tests that verifies the client behavior with respect to the protocol, (b) makes it more easier for language specialists to contribute and enhance existing implementations, (c) thus increasing adoption.

**Comment by vtolstov** [comment]
i think that issue can be closed....it outdated and i'm use sheepdog_proto.h for all wire messages to create compatible server

**Comment by neurodrone** [comment]
Sounds fair.
