### ISSUE TITLE
an option for disabling reconnection of the qemu driver

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#167]
requested by @devfaz

**Comment by mitake** [comment]
hi @devfaz , I created a branch for this topic: https://github.com/sheepdog/qemu/tree/reconnect-and-reload

Could you test it? You can disable reconnection with an option of QEMU like this: `-drive file=sheepdog:test,file.reconnection=off` .

In addition, the branch has a commit for introducing a new feature, retrying inode reload. If the option `file.reload-retry=on` is passed to qemu, qemu tries inode reloading in a case of snapshot if it cannot find a new inode object. If you can check this option doesn't harmful, it is a great help :)

**Comment by vtolstov** [comment]
@mitake why you not pull this to upstream now?

**Comment by mitake** [comment]
Let's close this for now because of the inactive state. Reopening is ok if somebody is interested in this.
