### ISSUE TITLE
sheep crashes with two qemu-img clients

### ISSUE THREAD

**Issue by hmex** [sheepdog/sheepdog#198]
I've compiled the latest sheep from git. Like this

./configure --prefix=/home/user/sys/sheepdog --enable-sheepfs --enable-trace --enable-debug --enable-corosync   --enable-assert --enable-trace
make clean ; make ; make install

I started sheep with 

/home/user/sys/sheepdog/sbin/sheep -c local /home/user/tmp/sheep/ -z 1 -p 7001 -r 127.0.0.1:4001

And started two qemu-img processes in two terminal windows

qemu-img convert sheepdog:OneMachine sheepdog:127.0.0.1:7001:OneMachine -p
qemu-img convert sheepdog:TwoMachine sheepdog:127.0.0.1:7001:TwoMachine -p

I started the second one after a few minutes, after confirming that the copy/convert process works and confirmed that ~/sys/sheepdog/sbin/dog vdi list -p 7001 shows increasing counters and in short the data is being copied. BUT AS SOON AS I started the second process sheep crashed and both processes were interrupted.

Here's the tail of the log (~/tmp/sheep/sheep.log)

Nov 25 21:12:37   WARN [main] event_handler_exit(44) timer_handler wastes too much time in event loop: 65592.90  us
Nov 25 21:12:39   WARN [main] event_handler_exit(44) timer_handler wastes too much time in event loop: 63484.871 us
Nov 25 21:12:41   WARN [main] event_handler_exit(44) timer_handler wastes too much time in event loop: 97774.681 us
Nov 25 21:12:44   WARN [main] event_handler_exit(44) timer_handler wastes too much time in event loop: 53271.56  us
Nov 25 21:12:44   WARN [main] event_handler_exit(44) timer_handler wastes too much time in event loop: 66151.804 us
Nov 25 21:12:45   INFO [main] rx_main(830) req=0x7f76340009d0, fd=24, client=127.0.0.1:45866, op=NEW_VDI, data=(not string)
Nov 25 21:12:45   WARN [main] event_handler_exit(44) worker_thread_request_done wastes too much time in event loop: 44083.357 us
Nov 25 21:12:45  EMERG [main] node_insert(122) PANIC: insert duplicate IPv6 ip::: port:0
Nov 25 21:12:45  EMERG [main] crash_handler(277) sheep exits unexpectedly (Aborted).
Nov 25 21:12:45  EMERG [main] sd_backtrace(833) mcount.S:46: trace_caller

There are MANY more messages about too much time wasted, but I didn't positively connect that to a specific malfunction, HOWEVER I had to restart sheep (I even had to resort to kill -9) after it locked up, vdi list worked but vdi create didn't. So far I wasn't able to determine what caused that.

And although I did --enable-debug, the -d option of sheep stopped working, which used to produce a lot more debugging information. And I noticed the lack of a stack backtrace, that could be because of ubuntu's restriction on ptrace. If you have trouble reproducing the issue yourself, I can try again with the ptrace filter disabled.

=== PS ====
I tried to cause the same crash again, but now it's copying. There are some funny messages in the log

Nov 25 21:39:27   INFO [main] recover_object_main(1057) object recovery progress -nan% 

But there is no recurrence of the "PANIC: insert duplicate IPv6 ip::: port:0" which I'm guessing might be relevant

=== PPS ====

The copying reached 100% but qemu-img isn't terminating, and now dog vdi create -p 7001 test 1G hangs. I.e. sheep is locked up somehwere. kill -TERM <pid> doesn't do anything. The log contains many 
WARN [main] event_handler_exit(44) timer_handler wastes too much time in event loop:
WARN [main] event_handler_exit(44) client_handler wastes too much time in event loop:
INFO [main] recover_object_main(1057) object recovery progress -nan%
WARN [main] event_handler_exit(44) worker_thread_request_done wastes too much time in event loop:

and the rest follows (after the original crash)

Nov 25 21:39:26   INFO [main] md_add_disk(368) /home/user/tmp/sheep/obj, vdisk nr 98, total disk 1
Nov 25 21:39:27   INFO [main] send_join_request(1042) IPv4 ip:127.0.0.1 port:7001 going to join the cluster
Nov 25 21:39:27   INFO [main] trace_init(428) trace support enabled. cpu count 4.
Nov 25 21:39:27 NOTICE [main] http_init(626) http service is not compiled
Nov 25 21:39:27 NOTICE [main] nfs_init(638) nfs server service is not compiled
Nov 25 21:39:27   WARN [main] check_host_env(526) Allowed open files 1024 too small, suggested 6144000
Nov 25 21:39:27   INFO [main] main(1007) sheepdog daemon (version 0.9.3_7_g796c88d) started
Nov 25 21:39:27   WARN [main] event_handler_exit(44) local_handler wastes too much time in event loop: 127230.969 us
Nov 25 21:40:51   INFO [main] rx_main(830) req=0x7f2d140008c0, fd=15, client=127.0.0.1:52352, op=NEW_VDI, data=(not string)
Nov 25 21:40:51   INFO [main] tx_main(882) req=0x7f2d140008c0, fd=15, client=127.0.0.1:52352, op=NEW_VDI, result=00
Nov 25 21:40:57   INFO [main] rx_main(830) req=0x7f2d140009d0, fd=25, client=127.0.0.1:52379, op=NEW_VDI, data=(not string)
Nov 25 21:40:57   INFO [main] tx_main(882) req=0x7f2d140009d0, fd=25, client=127.0.0.1:52379, op=NEW_VDI, result=00
Nov 25 21:41:15   INFO [main] rx_main(830) req=0x7f2cfc0008c0, fd=15, client=127.0.0.1:52441, op=DEL_VDI, data=(not string)
Nov 25 21:41:15   INFO [main] tx_main(882) req=0x7f2cfc0008c0, fd=15, client=127.0.0.1:52441, op=DEL_VDI, result=00
Nov 25 21:41:17   INFO [main] rx_main(830) req=0x7f2cfc0008c0, fd=22, client=127.0.0.1:52449, op=DEL_VDI, data=(not string)
Nov 25 21:41:17   INFO [main] tx_main(882) req=0x7f2cfc0008c0, fd=22, client=127.0.0.1:52449, op=DEL_VDI, result=00
Nov 25 21:41:28   INFO [main] rx_main(830) req=0x7f2d140008c0, fd=15, client=127.0.0.1:52483, op=NEW_VDI, data=(not string)
Nov 25 21:41:28   INFO [main] tx_main(882) req=0x7f2d140008c0, fd=15, client=127.0.0.1:52483, op=NEW_VDI, result=04
Nov 25 21:41:38   WARN [main] event_handler_exit(44) local_req_handler wastes too much time in event loop: 28974.985 us
Nov 25 21:41:39   INFO [main] rx_main(830) req=0x7f2cd00008c0, fd=15, client=127.0.0.1:52510, op=DEL_VDI, data=(not string)
Nov 25 21:41:39   INFO [main] tx_main(882) req=0x7f2cd00008c0, fd=15, client=127.0.0.1:52510, op=DEL_VDI, result=00
Nov 25 21:41:42   INFO [main] rx_main(830) req=0x7f2cfc0008c0, fd=15, client=127.0.0.1:52529, op=NEW_VDI, data=(not string)
Nov 25 21:41:42   INFO [main] tx_main(882) req=0x7f2cfc0008c0, fd=15, client=127.0.0.1:52529, op=NEW_VDI, result=00
Nov 25 21:41:48   INFO [main] rx_main(830) req=0x7f2cd80008c0, fd=23, client=127.0.0.1:52554, op=NEW_VDI, data=(not string)
Nov 25 21:41:48   INFO [main] tx_main(882) req=0x7f2cd80008c0, fd=23, client=127.0.0.1:52554, op=NEW_VDI, result=00
Nov 25 22:22:03   INFO [main] rx_main(830) req=0x7f2ce40009d0, fd=29, client=127.0.0.1:59466, op=NEW_VDI, data=(not string)
Nov 25 22:42:48   INFO [main] rx_main(830) req=0x7f2d140009d0, fd=34, client=127.0.0.1:34940, op=NEW_VDI, data=(not string)

=== PPPS ====

It crashed again, when a third client connected. /proc/.../ptrace_scope was set to 0, still no trace, that might be a separate problem. Maybe I didn't compile something in? But the last messages in the log are:

Nov 25 22:56:17   INFO [main] rx_main(830) req=0x7fef2c000ae0, fd=29, client=127.0.0.1:37835, op=NEW_VDI, data=(not string)
Nov 25 22:56:18   WARN [main] event_handler_exit(44) worker_thread_request_done wastes too much time in event loop: 164049.227 us
Nov 25 22:56:18  EMERG [main] node_insert(122) PANIC: insert duplicate IPv6 ip::: port:0
Nov 25 22:56:18  EMERG [main] crash_handler(277) sheep exits unexpectedly (Aborted).
Nov 25 22:56:18  EMERG [main] sd_backtrace(833) mcount.S:46: trace_caller

Again the PANIC: insert duplicate IPv6 ip::: port:0

That's it, I'm done for now, let me know if I can provide further data. Obviously for now I'm staying with 0.7.5, since it only seems to have a problem with the cache.

**Comment by mitake** [comment]
@hmex thanks for your report. The tracing feature is just for development purpose, so please turn off it with --disable-trace.

> Nov 25 21:39:27 INFO [main] recover_object_main(1057) object recovery progress -nan%

The above message is strange. It should be solved.

**Comment by hmex** [comment]
how about the fact that sheep sometimes crashes after additional qemu-img clients connect to it? I think that's much more serious. The bad calculation of percentages is merely a nuisance, while the crash is a show stopper. Are you able to reproduce it? Or are you saying that the --enable-trace caused it?

**Comment by mitake** [comment]
I'm not sure about the crash problem, I cannot reproduce the problem on my env. Could you try to reproduce the problem without --enable-trace?

**Comment by hmex** [comment]
I think the same crash isn't happening now, but I've managed to crash it differently. I've been putting sheep through heavy load. Maybe a dozen qemu-img convert from a file, and hundreds or maybe a thousand dog vdi create and a few dog vdi delete all concurrently. To me the crash looks different, but it's still a crash. At the time of the crash there were 1889 VDIs present. Any idea why it crashed this time? bus error might mean SIGBUS, which according to the man page is "bad memory access". 

After a number of messages that aren't any different from when sheep is working there are two lines, the last two lines before a crash:
Dec 04 12:24:05  EMERG [main] crash_handler(277) sheep exits unexpectedly (Bus error).
Dec 04 12:24:06  EMERG [main] sd_backtrace(833) mcount.S:46: trace_caller

**Comment by hmex** [comment]
but after the sheep was restarted and I attempted to create another few thousand VDIs sheep locked up, the last log message is below, doesn't look helpful. Right now dog vdi list works, but dog vdi delete and dog vdi create hang. There are about 1000 dog vdi create processes, all waiting for input from socket (strace -p $DOG_PID). And kill -TERM $SHEEP_PID doesn't have an effect, nor does HUP.

**Comment by mitake** [comment]
@hmex sorry for my late reply. I think the below logs
> Dec 04 12:24:05 EMERG [main] crash_handler(277) sheep exits unexpectedly (Bus error).
> Dec 04 12:24:06 EMERG [main] sd_backtrace(833) mcount.S:46: trace_caller
are produced by the tracing feature. Could you rebuid your sheep with --disable-trace and retry?

Seems that the log level of your cluster is debug. Could you restart with log level info (default)? It will reduce the amount of logs. If the problem disappears, we should doubt the log rotation mechanism.

**Comment by vtolstov** [comment]
more then 2 years... please close, and if problem persists we can reopen/open new issue for it
