### ISSUE TITLE
remove xmalloc() from gateway.c

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#207]
Some functions in sheep/gateway.c call xmalloc() in hotpath. In a case of failed allocation, it will kill sheep so the function shouldn't be called. Instead of calling xmalloc(), the gateway path should return SD_RES_NO_MEM.

**Comment by mitake** [comment]
@tmenjo if you have a time, could you work on this issue?

**Comment by tmenjo** [comment]
@mitake sure, I'm going to work on the issue.

**Comment by tmenjo** [comment]
@mitake:
How about **xcalloc(), xvalloc() and xzalloc()**?

I think we should also remove these function
because they will panic() when memory allocation failed.
They are called in some functions in sheep/gateway.c too.

**Comment by mitake** [comment]
@tmenjo sure, they also should be excluded from hot path.
