### ISSUE TITLE
Performance influence of node recovery

### ISSUE THREAD

**Issue by gangzai** [sheepdog/sheepdog#223]
Dear all,
        
          How to reduce the performance influence of node recovery in production environment？

**Comment by mitake** [comment]
@gangzai you can throttle the recovery traffic with `dog node set-throttle` command.

@tmenjo do you have an example data of recovery throttling?

**Comment by gangzai** [comment]
@mitake Thanks a lot! I will try it.

**Comment by tmenjo** [comment]
@mitake Sorry, but I don't have such data of recovery throttling.

**Comment by gangzai** [comment]
@tmenjo Thank you all the same!
