### ISSUE TITLE
doc: document about 'dog cluster format -F'

### ISSUE THREAD

**Issue by tmenjo** [sheepdog/sheepdog#238]
A new feature is introduced from commit 8c888c0. This is to avoid diskfull caused by recovery process. We can use this with ```dog cluster format -F```.

To use this feature properly, it should be documented when and why this is or is NOT effective.

### Related pull requests and issues:

* sheep: avoid diskfull caused by recovery process #185 ([My suggestion](https://github.com/sheepdog/sheepdog/pull/185#issuecomment-214671328) and [mitake's reply](https://github.com/sheepdog/sheepdog/pull/185#issuecomment-214943477))
* Disable recovery when there's not enough space #59

**Comment by matsu777** [comment]
I wrote the documentation about this issue and made PR #248.

**Comment by matsu777** [comment]
I closed PR #248 because I committed the wrong(old) documentation.
I made new PR #249 with the modified documentation.
