### ISSUE TITLE
No "next patch" in latest stable-0.9

### ISSUE THREAD

**Issue by tmenjo** [sheepdog/sheepdog#243]
After tagged with v0.9.3, some commits have been applied into [stable-0.9](https://github.com/sheepdog/sheepdog/tree/stable-0.9) branch. Its latest commit 796c88d *"sheep: update ledger objects in an asynchronous manner"* says (emphasis mine):

> This patch let gateway update ledger objects in an asynchronous manner. This change improves performance of COW and dereferencing. Especially vdi deletion will be improved.
> 
> Of course this change introduces a chance of inconsistency of metadata, but but sheepdog is a distributed file system without metadata journaling. Therefore inconsistency of metadata introduced by machine crash or network error, etc must be solved by methods like fsck (dog vdi check, etc). For this purpose, **the next patch** enhances VID GC for collecting garbage objects which belong to removed VDIs.

However there is no "next patch" in stable-0.9. So I am afraid that latest stable-0.9 is not stable and think that we should use not stable-0.9 but v0.9.3 if we need stable Sheepdog ASAP.

May I have your idea, @mitake?

(I think the "next patch" is ecdb602 *"sheep: clean leaked object during recycling VID."* This is not applied into stable-0.9 but already applied into master, so I'm not afraid of this for v1.0.)

**Comment by mitake** [comment]
The next patch introduces incompatibility in VID management. So we cannot backport it to stable-0.9. The patch you mentioned (update ledger objects...) is independent from the next one, so stable-0.9 is safe.

BTW, releasing v0.9.4 would be ready. If it is possible, could you work on the releasing process?

**Comment by tmenjo** [comment]
@mitake: Sure, I will open a PR for v0.9.4 in a few days. I will be glad if you review the PR.
