### ISSUE TITLE
Format of data_vdi_id in dump-inode

### ISSUE THREAD

**Issue by Tbabm** [sheepdog/sheepdog#246]
Is it better to use `PRIx32` instead of `PRIu32` to print `inode->data_vdi_id[i]` in dump-inode?

```c
/* dog/vdi.c vdi_object_dump_inode(2578) */

printf("%d: %"PRIu32"\n", i, inode->data_vdi_id[i]);
```

**Comment by mitake** [comment]
@Tbabm ah, yes, the hex format is better. Could you create a PR?
