### ISSUE TITLE
kvm segfault under heavy IO

### ISSUE THREAD

**Issue by douardda** [sheepdog/sheepdog#26]
I have a testing sheepdog setup consisting of 3 nodes which are also kvm hosts. I am using Debian squeeze with backports and sheedog built from git (at rev 86a25e9b0308ae67821e7fb6b79f51f2841fb745). The sheepdog storage is formatted with 2 copies of the data.

Installed packages on the nodes:

  qemu-kvm                          1.0+dfsg-8~bpo60+1
  linux-image-3.2.0-0.bpo. 3.2.4-1~bpo60+1

VMs are started with libvirt.

I do not have much logs but the segfault in syslog like:

> kvm[17438]: segfault at 401390 ip 00007fd16f3e04d1 sp 00007fd17441fb60 error 4 in kvm

Note that I also have a "reference" VM running on one node of the cluster using a raw image disk as storage that do not segfault.

Is this a known issue? 

David

**Comment by vtolstov** [comment]
No replies for 2 years, may be close?

**Comment by douardda** [comment]
I'm not using sheepdog anymore for now and I have not tested this bug recently.
Sorry

**Comment by vtolstov** [comment]
Close the issue please.
26 мая 2015 г. 11:45 пользователь "David Douard" <notifications@github.com>
написал:
