### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [sheepdog/sheepdog#30]
Would you like to replace more defines for constant values by [enumerations](http://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [```SD_OP_```...](https://github.com/collie/sheepdog/blob/2df7550fe04c418bdcf78d18b580b345d2503353/include/sheep.h#L31)
* [```SD_RES_```...](https://github.com/collie/sheepdog/blob/c6c72cbaa01ec6ea0d9f2099b970231e1f2dbde4/include/sheepdog_proto.h#L38)

**Comment by vtolstov** [comment]
@mitake what do you think about this? As i see this is trivial change, do we need this?

**Comment by mitake** [comment]
I don't think define them with enum is a good idea. Some logs have their value in hex, so defining their value explicitly would be better.
