### ISSUE TITLE
NEW FEATURE for 1.0

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [sheepdog/sheepdog#304]
Someone can  update CHANGELOG.md about the NEW FEATURE for 1.0 ?

**Comment by mitake** [comment]
@zhengxiaochuan-3 really sorry for my late reply, @tmenjo do you have a time for working on it?

**Comment by tmenjo** [comment]
@mitake: Sure. I will go the work on [my branch](https://github.com/tmenjo/sheepdog/blob/changelog-v1.0/CHANGELOG.md).
