### ISSUE TITLE
"No object found" when trim with are live migrating

### ISSUE THREAD

**Issue by Paucpauc** [sheepdog/sheepdog#311]
If you execute fstrim when are migrating, the vdi break with error "ERROR [gway 31894] wait_forward_request(470) fail bac502000000e1, No object found".

```
root@web-mr-test08:~# dd if=/dev/zero of=big bs=1M ; sync            
dd: error writing 'big': No space left on device
596+0 records in
595+0 records out
624181248 bytes (624 MB) copied, 2.28861 s, 273 MB/s

(Start migration # virsh migrate --verbose --live web-mr-test08 qemu+ssh://web-mr-vmm02/system)
root@web-mr-test08:~# rm big ; sync ; sleep 1 ; fstrim -v / ; sync   
/: 640962560 bytes were trimmed
(Wait for migration completed)

root@web-mr-test08:~# dd if=/dev/zero of=big bs=1M oflag=direct
dd: error writing 'big': Input/output error
5+0 records in
4+0 records out
4194304 bytes (4.2 MB) copied, 0.382821 s, 11.0 MB/s
```

Sheepdog args - "-n -D"
QEMU args - "-drive file=sheepdog:127.0.0.1:7000:web-mr-test08,format=raw,if=none,id=drive-scsi0-0-0-0,cache=none,discard=unmap,aio=native"
Sheepdog daemon (version 1.0), QEMU emulator version 2.7.0

**Comment by mitake** [comment]
Does this error happen if you don't invoke the live migration?

**Comment by Paucpauc** [comment]
No. The error only occurs if call the trim during migration. Reproduced with 100% probability.

**Comment by mitake** [comment]
Thanks. Is trimming during live migration needed for your usecase?

**Comment by vtolstov** [comment]
2016-09-29 8:35 GMT+03:00 Hitoshi Mitake <notifications@github.com>:

> Thanks. Is trimming during live migration needed for your usecase?


I think this is unrelated to host admin. If i enable discard on mounpoint
inside vm it does trim/discard anytime then i delete file.



-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by Paucpauc** [comment]
Yes. If the discard enabled on the mount point, then trim may triggered on each unlink.

**Comment by vtolstov** [comment]
@mitake @tmenjo does this qemu side error or sheep ?

**Comment by mitake** [comment]
@vtolstov I'm not sure but let's close this for now because of the inactive state.
