### ISSUE TITLE
'man collie' unclear on effect of '--mode' option

### ISSUE THREAD

**Issue by struanb** [sheepdog/sheepdog#33]
The manpage says:
       -m, --mode [safe|quorum|unsafe]
              This option controls the behavior when there are too few nodes for the configured redundancy. Mode 'safe' will halt cluster IO  when  (nr_nodes  <  nr_copies).
              Mode 'quorum' will halt cluster IO when (nr_nodes < nr_copies/2 + 1). Mode 'unsafe' will never halt the cluster and therefore data loss may result.

The last line implies data loss cannot occur with quorum or safe mode, yet it's unclear why data loss would occur if only 1 node was available (when data may be read/written just fine?); or even if 0 nodes were available (when cluster IO is therefore effectively halted).

**Comment by vtolstov** [comment]
@mitake this option is gone sometimes ago, please, close the issue.
