### ISSUE TITLE
object ID should be printed in the form of `"%016" PRIx64` to sheep.log

### ISSUE THREAD

**Issue by tmenjo** [sheepdog/sheepdog#340]
An object file has 16-digit zero-padded hexadecimal name corresponding to its 64-bit OID (if we use plain_store or tree_store, at least). However, it is not printed like that in sheep.log. [For example](https://github.com/sheepdog/sheepdog/blob/master/sheep/recovery.c#L639):

```c
sd_err("failed to recover object %"PRIx64, oid);
```

I think every object name should also be printed in the form of 16-digit zero-padded hexadecimal, that is, `"%016" PRIx64`. It is operator-friendly because she or he can tell whether that object is a data object (00...) or an inode object (80...) simply by looking at its name.

**Comment by mitake** [comment]
It seems to be a good idea, could you create a PR for the change?
