### ISSUE TITLE
Sheepdog on top of ZFS

### ISSUE THREAD

**Issue by vjason** [sheepdog/sheepdog#35]
I am trying to run Sheepdog on top of a ZFS mount point.  I keep getting an error:  

Jan 01 12:12:14 [main] queue_request(354) CREATE_AND_WRITE_OBJ, 1
Jan 01 12:12:14 [gway 232] do_process_work(1233) 1, ad75c000003ff, 1
Jan 01 12:12:14 [gway 232] gateway_forward_request(262) ad75c000003ff
Jan 01 12:12:14 [gway 232] default_create_and_write(320) failed to open /var/lib/sheepdog/disc0/obj/000ad75c000003ff.tmp: Invalid argument
Jan 01 12:12:14 [gway 232] err_to_sderr(128) oid=ad75c000003ff, Invalid argument
Jan 01 12:12:14 [gway 232] gateway_forward_request(302) fail to write local 3
Jan 01 12:12:14 [gway 232] gateway_forward_request(307) nr_sent 0, err 3
Jan 01 12:12:14 [gway 232] do_process_work(1240) failed: 1, ad75c000003ff , 1, 3
Jan 01 12:12:14 [main] gateway_op_done(99) leaving sheepdog cluster

I can write to the mount point as a user.  I also have made sure that xattr is turned on on the zfs filesystem.   Is there something else I am missing?

I have verified that that sheepdog works fine with a ext3 filesystem.

**Comment by vtolstov** [comment]
As I see issue solved disabling directio and may be closed

**Comment by vtolstov** [comment]
@mitake issue solved.
