### ISSUE TITLE
Sheepdog+sheepfs - can't mount volume

### ISSUE THREAD

**Issue by thug-nick** [sheepdog/sheepdog#36]
Good day.
I've done all as described in instructions (Ubuntu 12.04+CentOS 6.3). 
Setuped corosync on internal network 10.10.10.* (corosync address in config is 10.10.10.0), in logs: 
Feb 01 12:50:52 corosync [CPG   ] chosen downlist: sender r(0) ip(10.10.10.13) ; members(old:2 left:0)
Feb 01 12:50:52 corosync [MAIN  ] Completed service synchronization, ready to provide service.
Setuped sheepdog by: 
sheep /mnt (or /home to test)
collie cluster format --copies=3
[root@host log]# collie node list   
M   Id   Host:Port         V-Nodes       Zone
-    0   10.10.10.13:7000       64  218761738
-    1   10.10.10.14:7000       64  235538954
-    2   10.10.10.15:7000       64  252316170

Then sheepfs:
sheepfs /home/sheep/fs/ 
[root@host log]# cat /home/sheep/fs/cluster/info
Cluster status: running
Cluster created at Fri Feb  1 12:52:15 2013
Epoch Time           Version
2013-02-01 12:52:15      1 [10.10.10.13:7000, 10.10.10.14:7000, 10.10.10.15:7000]

And now it's time to mount a volume: 
echo test > /home/sheep/fs/vdi/mount or echo test > /mnt/fs/vdi/mount (ubuntu nodes)
The result is: bash: echo: write error: Invalid argument, tried to insert "test" by vi to the file - can't save file. 
What am I doing wrong? 
Thanks and best regards, Nikolay.

**Comment by vtolstov** [comment]
@thug-nick add to sheepfs wiki, please close issue.
@mitake may be we need recheck wiki pages?

**Comment by mitake** [comment]
yes, our wiki has many outdated contents...
