### ISSUE TITLE
Some sheepdog questions

### ISSUE THREAD

**Issue by phillipp** [sheepdog/sheepdog#37]
Hi,
i would like to test and deploy sheepdog as our VM disk backend because it looks like a great project, but I have some questions first:

1. we have a very mixed cluster with different disk sizes, disk performances and cpu performances. Will this be a problem? Should I use only use disks/hosts with the same size?
2. "Cluster management: good practices -> General remarks" doc says that I will data loss, if I restart multiple sheeps at once? I think I'm not getting it right: I will expericence permanent data loss and/or corruption of the images if I shut down multiple nodes and start them later? Or is this just "in flight IO" that I will lose?
3. Is it safe to put the sheepdog storage on a partition that is in use by other applications too? Should I create an extra partition (eg for sheepdog to calculate free cluster space)?
4. Are there any backup best practices? Snapshot, dump & compress image, remove snapshot?

Thanks,
Phillipp

**Comment by vtolstov** [comment]
May be close issue?

**Comment by vtolstov** [comment]
@mitake as i see all questions answered, so please close this issue
