### ISSUE TITLE
rpm: proposal for sub-package separation.

### ISSUE THREAD

**Issue by kazuhisya** [sheepdog/sheepdog#374]
I would like to propose separating rpm in the main-package and sub-packages.
Currently, `sheepdog` rpm package may or may not include zookeeper, corosync or sheepfs depending on the build environment.
So, in spite of completely same package name, it is a problem that artifacts with different options are created.
By separating sub-packages, users can choose the module they only need. I think that would be better.

Specifically, it will separates like follows. (draft)

1. `sheepdog` (main)
2. `sheepdog-devel` and/or `sheepdog-libs` (not necessary?)
3. `sheepdog-zookeeper` (or `sheepdog-zk-util` ?)
4. `sheepdog-fuse` (or `sheepdog-sheepfs` ?)
* separation of `corosync`, `http`, `nfs` ... may be a bit difficult now. (this reason is that rpm is based on file-based separation.)

Anyway, this change may affect documents and users.
How do you think?

(refs #373)

**Comment by mitake** [comment]
@kazuhisya Thanks for your proposal. The idea seems to be attractive. The rpm dependency problems aren't solved currently because we don't have enough resource. If you can work on this, it will be very helpful.

/cc @tmenjo @yamada-h @marcin-github

**Comment by ikedaj** [comment]
I added the complementary patch as #375 to pull request #373
and I can build rpm without corosync for now.
Would you check this?

# ./autogen.sh && \
  ./configure --disable-corosync --enable-zookeeper && \
  make clean rpm

Is there any corosync dependencies outside of building sequence?

By the way, the main reason why I need --disable-corosync,
there is some possibility of running sheepdog v1.0.x on RHEL 6.
RHEL 6 has corosync 1.x and sheepdog v1.0.x need corosync >= 2.
I know that it would be better to use the latest OS(RHEL 7) 
and it's still undecided which version combination would come,
I just want to have some choices.

**Comment by kazuhisya** [comment]
@mitake Thank you for your reply.
Then, I will try to start work based on this draft. (I do not know for sure if it will be in time for v1.0.2GA release…)


@ikedaj I checked #373, #375. and it's seems good.
On the other hand, I think that the motivation for separating packages is that user can easily combine sheepdogs feature by choosing the released official rpm package. this is a scenario where users just install `.rpm` without building.

**Comment by ikedaj** [comment]
@kazuhisya
I think your proposal is really reasonable, and it would be helpful to users.
My patch is just for the particular environment.

**Comment by kazuhisya** [comment]
#378 has been merged, so I would like to close this issue.
Thanks a lot!
