### ISSUE TITLE
dog error with stacktrace

### ISSUE THREAD

**Issue by AdUser** [sheepdog/sheepdog#382]
Steps to reproduce:

* setup sheepdog cluster with 3 nodes
* format cluster with  `-c 2` defaults (maybe unrelevant)
* shutdown one node
* create a test vdi with -c 2:1 (should sheepdog allow this? now we have only two nodes up)
* execute `dog vdi object location test`

Example stacktrace:

```
# dog vdi object location test                          
Looking for the inode object 0x7c2b25 with 2 nodes

192.168.7.5:7000 has the object
192.168.7.6:7000 has the object

According to sheepdog algorithm, the object should be located at:
PANIC: can't find a valid vnode
dog exits unexpectedly (Aborted).
dog(+0xb44e) [0x7f5f1dc6444e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf09f) [0x7f5f1d82a09f]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x34) [0x7f5f1d09f124]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x17f) [0x7f5f1d0a239f]
dog(+0x107ed) [0x7f5f1dc697ed]
dog(+0x132f6) [0x7f5f1dc6c2f6]
dog(+0xcd3c) [0x7f5f1dc65d3c]
dog(main+0x72f) [0x7f5f1dc6181f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfc) [0x7f5f1d08beac]
dog(+0x8c80) [0x7f5f1dc61c80]
```

Reproducible at least with 0.9.2, maybe later.

**Comment by mitake** [comment]
@AdUser thanks for your report. I'll work on it later.

**Comment by mitake** [comment]
@AdUser the problem was already fixed in the latest master. Could you try the master branch?

**Comment by AdUser** [comment]
@mitake

Unfortunately i don't have another cluster for experiments. But i'm glad to hear, that bug has been already fixed. Thx.
