### ISSUE TITLE
Tests on RHEL-based distribution?

### ISSUE THREAD

**Issue by kazuhisya** [sheepdog/sheepdog#395]
For now, sheepdog tests case(`/tests`) seems to be made on only can executed by ubuntu.
But, I usually use RHEL(and  CentOS). So, I would like to be able to run it on CentOS too.

How do you think?

**Comment by mitake** [comment]
If CentOS can be supported by the testing scripts, it is very nice and the changes will be welcomed.

**Comment by kazuhisya** [comment]
@mitake Thank you for a reply.
I began my work, so I will make a PR when it is ready.

**Comment by kazuhisya** [comment]
Thank you for merged the PR, I close this issue.
