### ISSUE TITLE
"collie node list" cannot list the other server

### ISSUE THREAD

**Issue by turbo73** [sheepdog/sheepdog#40]
as the topic,i have 2 server in my LAN(all installed sheepdog),but one can not see  the other in "collie node list" , like this:

[root@kvm-1 ~]# collie node list
M   Id   Host:Port         V-Nodes       Zone
-    0   172.18.11.192:7000  	64-1073016148

[root@kvm-2 ~]# collie node list
M   Id   Host:Port         V-Nodes       Zone
-    0   172.18.11.198:7000  	64 -972352852

and i had stop my iptables & selinux, but it still just can see itself.. help me please,thanks a lot!

**Comment by vtolstov** [comment]
@mitake as for my testing (i'm use corosync 2.x) this not happening, may be we need close this outdated issue?

**Comment by mitake** [comment]
thanks for checking, I'm closing it.
