### ISSUE TITLE
deprecate and replace accelio

### ISSUE THREAD

**Issue by vtolstov** [sheepdog/sheepdog#405]
I'm happy with first steps with adding rdma to sheepdog, but as https://github.com/accelio/accelio/issues/208 mellanox not want to fix bugs..

**Comment by byronyi** [comment]
I think go for [rdmacm](https://github.com/linux-rdma/rdma-core/tree/master/librdmacm) would be just as fine. Mellanox clearly has no idea what they are doing. They are making [the single worst mistake](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/), and they claimed UCX as an alternative which has no release up till now whatsoever.

**Comment by vtolstov** [comment]
@byronyi yes, i think so too. I'm check libfabric also, but not understand benefits of it.

**Comment by byronyi** [comment]
@vtolstov I actually just spent several days looking into libfabrics, but I have not found any benefits to use it for our RoCE network. It seems more like a fancier API to replace rdmacm/ibverbs, but the advanced features are for Intel and other new hardwares only.

But their [guide}(https://github.com/ofiwg/ofi-guide/blob/master/OFIGuide.md), though incomplete, is really well-written and worth reading.

I will probably stick to rdmacm/ibverbs for my current project.

**Comment by vtolstov** [comment]
thanks for info
