### ISSUE TITLE
How many clients(arm use sbd driver) are supported?

### ISSUE THREAD

**Issue by brizzard** [sheepdog/sheepdog#428]
hi ,we are testing the sheepdog with android's arm device, using sbd.
The test cluster include 1 gateway and 4 sheep store nodes.
But we found that it only supported about 4,000 devices. All sheep demon start with default args.
Of couse we excluded the server's configuration reasons.(ulimit and other thing...maybe)
the EPOLL_SIZE in sheep.c is 4096, I changed it but ineffective.
so, is there any suggests? how to “unlimit” it?  Thanks For All

**Comment by brizzard** [comment]
sorry, the client's dmesg log is : sbd0:unknown partition table

**Comment by vtolstov** [comment]
main problem that sbd is writed long time ago and not maintained =(

**Comment by brizzard** [comment]
Thanks for reply
ummm...but the first 4000 clients works well. Only newcomers reported the error.
If I disconnected some "old" clients, the new client will work fine.
It lools like there is some limit in the sheep daemon. 
with tcpdump,I find the new sbd connect gateway succ and gw also returned data,then the sbd close the socket and report  "unknown partition table".....
It looks like the returned data is incomplete？I've read the code but found nothing about that.

**Comment by brizzard** [comment]
We tried again. The epoll_size is effective.
