### ISSUE TITLE
command option 'localhost' support

### ISSUE THREAD

**Issue by chenjinzhi** [sheepdog/sheepdog#47]
when I run `dog vdi list -a localhost`, it displays:
\# Invalid ip address localhost
It seems that sheepdog doesnot support localhost option.
And I think the option is necessary. Some up-level program may generate `dog vdi create XXXX -a localhost` command when using sheepodog as backend suppport.
So I suggest maybe we can add 'localhost' option support in dog.c. Just add a simple judge statement in "getopt_long switch case 'a' statment" works well. Maybe there is better solution.
Thanks.

**Comment by vtolstov** [comment]
i think we need to rewrite str_to_addr to use getaddrinfo, but i don't understand how to not slowdown other things.
@mitake how the best add ability to specify not only ip address but also hostnames ?
Also this is very useful to support AF_IB sockets in RDMA.

**Comment by vtolstov** [comment]
my pr use only first available address, so if node have many addresses, may be good to try connect to each address, and pas only worked ip...

**Comment by vtolstov** [comment]
@mitake does this pr have problems?

**Comment by mitake** [comment]
@vtolstov hmm, I couldn't find your PR (I could found your local commit). Could you create a PR again?

**Comment by vtolstov** [comment]
@mitake i think i forgot to create pr, now all ok =)
