### ISSUE TITLE
make an improved integration with libvirt daemon and virt-manager for latest release

### ISSUE THREAD

**Issue by dmnord** [sheepdog/sheepdog#58]
Hello!

Recently I 've tried to setup a sheepdog storage using Fedora 22 and its libvirt and virt-manager packages. Currently this distribution has a libvirt 1.2.17 and virt-manager 1.2.0.

During my testcases, I 've successfully built an rpm package of sheepdog 0.9.2 taken from github repo.
Also I 've configured sheepdog with corosync cluster.

When I try to connect within virt-manager to sheepdog cluster remotely, I get errors while checking  parameters to connect to sheepdog storage. I 've tried to use your wiki https://github.com/sheepdog/sheepdog/wiki/Libvirt, but it doesn't work with explanation.

Help, if you have enough time!

**Comment by vtolstov** [comment]
What errors you get?please provide logs.
30 июля 2015 г. 18:48 пользователь "dmnord" <notifications@github.com>
написал:

**Comment by dmnord** [comment]
Hi! My test environment is 2-node corosync cluster with sheepdog storage (I described it before).
Every node has an address 192.168.100.x (x is 11 and 12 in fourth oktet)

Sheepdog cluster works fine as I guess:

[[Node 1]]
[root@sheep-node-01 ~]# dog node list
  Id   Host:Port         V-Nodes       Zone
   0   192.168.100.11:7000 	 4  191146176
   1   192.168.100.12:7000 	 4  207923392
[root@sheep-node-01 ~]# dog node md info
Id	Size	Used	Avail	Use%	Path
 0	4.5 GB	0.0 MB	4.5 GB	  0%	/sheep/disk/0
 1	4.5 GB	0.0 MB	4.5 GB	  0%	/sheep/disk/1

[[Node 2]]
[root@sheep-node-02 ~]# dog node list
  Id   Host:Port         V-Nodes       Zone
   0   192.168.100.11:7000 	 4  191146176
   1   192.168.100.12:7000 	 4  207923392
[root@sheep-node-02 ~]# dog node md info
Id	Size	Used	Avail	Use%	Path
 0	4.5 GB	0.0 MB	4.5 GB	  0%	/sheep/disk/0
 1	4.5 GB	0.0 MB	4.5 GB	  0%	/sheep/disk/1

I also installed a libvirt daemon on that nodes and connect to ones within virt-manager remotely from my desktop.

Look at my screenshots when I try to get an access to a sheepdog storage via virt-manager.

![00-virt-manager-connection-details-dialog-screen](https://cloud.githubusercontent.com/assets/12894352/9000823/7b7d9368-376f-11e5-85e7-860b9b8a2f20.png)
![01-virt-manager-create-storage-step1](https://cloud.githubusercontent.com/assets/12894352/9000790/c6bc2282-376e-11e5-9331-bce188544011.png)
![02-virt-manager-create-storage-step2-only-hostname](https://cloud.githubusercontent.com/assets/12894352/9000792/c6c12b7e-376e-11e5-90de-dd3d27a22429.png)
![03-virt-manager-create-storage-step2-with-port](https://cloud.githubusercontent.com/assets/12894352/9000793/c7247a80-376e-11e5-9bae-197c34abadbc.png)
![04-virt-manager-create-storage-result-always](https://cloud.githubusercontent.com/assets/12894352/9000806/0ba2872e-376f-11e5-98f7-7d50afe9f947.png)

**Comment by vtolstov** [comment]
As I see, libvirt builded without sheepdog or you need to install some
packages for sheepdog libvirt support.
31 июля 2015 г. 7:50 пользователь "dmnord" <notifications@github.com>
написал:

**Comment by dmnord** [comment]
The libvirt was built via rpm package with option --with-storage-sheepdog. While installation process, libvirt package also installs a sheepdog package as a requirement.

Libvirt doesn't use any library for working with sheepdog. That is why, libvirt works with sheepdog directly though executable binary (dog command). I saw that in python code of libvirt.

Missing dependencies is not a real problem!

**Comment by vtolstov** [comment]
2015-07-31 13:44 GMT+03:00 dmnord <notifications@github.com>:

> The libvirt was built via rpm package with option --with-storage-sheepdog.
> While installation process, libvirt package also installs a sheepdog
> package as a requirement.
>
> Libvirt doesn't use any library for working with sheepdog. That is why,
> libvirt works with sheepdog directly though executable binary (dog
> command). I saw that in python code of libvirt.
>
> Missing dependencies is not a real problem!
>

Please provide full build log for this rpm so we can understand how libvirt
build.


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by vtolstov** [comment]
2015-07-31 13:49 GMT+03:00 Vasiliy Tolstov <v.tolstov@selfip.ru>:
> Please provide full build log for this rpm so we can understand how libvirt
> build.


alse please provide output for virsh -V on node where libvirt running

-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by dmnord** [comment]
I apologizing, I was sure that standard rpm package always compiles with sheepdog. Also installing sheepdog with libvirt as requirement is not rule.

The command virsh -V shows me:
[root@sheep-node-01 /]# virsh -V | grep Storage
 Storage: Dir Disk Filesystem SCSI Multipath iSCSI LVM RBD Gluster

Sheepdog support is absent here.

**Comment by dmnord** [comment]
I'd like to ask a last quiestion about setting of volume in the libvirt.

What the source name on screens 2 and 3 means?
Sheepdog hasn't any source name.

**Comment by vtolstov** [comment]
2015-07-31 14:03 GMT+03:00 dmnord <notifications@github.com>:

> I'd like to ask a last quiestion about setting of volume in the libvirt.
>
> What the source name on screens 2 and 3 means?
> Sheepdog hasn't any source name.
>

Source is like key, enter what you want. My xml for sheepdog looks like:
<pool type='sheepdog'>
  <name>sheepdog</name>
  <source>
    <host name='127.0.0.1' port='7000'/>
    <name>sheepdog</name>
  </source>
</pool>


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by dmnord** [comment]
Thanks a lot for your help. Will try some tests right now.

**Comment by vtolstov** [comment]
@dmnord i think this issue can be closed.

**Comment by dmnord** [comment]
I found a littile mistake in spec-file for Fedora. I already fixed that for my needs.
I think you right, the issue you may close.

**Comment by vtolstov** [comment]
@dmnord i dont' have this rigts =) so only you and @mitake can close.

**Comment by zahradehghanpur** [comment]
I am facing the same issue , any update on support sheepdog in libvirt?

**Comment by vtolstov** [comment]
Sheepdog unmaintained now
