### ISSUE TITLE
update build script of libvirt

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#67]
it depends on collie command.

related thread:
http://lists.wpkg.org/pipermail/sheepdog/2014-June/015097.html

**Comment by vtolstov** [comment]
New libvirt have my patch and auto determine command. So libvirt 1.2.18
have this patch.
01 авг. 2015 г. 8:37 пользователь "Hitoshi Mitake" <notifications@github.com>
написал:

**Comment by mitake** [comment]
Thanks a lot for the patch!
