### ISSUE TITLE
dog: segmentation fault occurs when omitting the "dog node log level " sub command

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#77]
I found that a segmentation fault occurs when I omit the "dog node log level " subcommand and specify option .
I give 2 examples.

・I omit subcommand (get, set, list), and specify -a option.

$ dog node log level -a 127.0.0.1
dog exits unexpectedly (Segmentation fault).
dog.c:356: crash_handler
/lib64/libpthread.so.0() [0x36efe0f4ff]
/lib64/libc.so.6() [0x36efb36d99]
common.c:245: do_generic_subcommand
common.c:261: do_generic_subcommand
dog.c:524: main
/lib64/libc.so.6(__libc_start_main+0xfc) [0x36efa1ecdc]
dog() [0x403138]
segmentation fault

・I specify "set" subcommand and specify -a option.

$ dog node log level set -a 127.0.0.1
dog exits unexpectedly (Segmentation fault).
dog.c:356: crash_handler
/lib64/libpthread.so.0() [0x36efe0f4ff]
/lib64/libc.so.6() [0x36efb36eb3]
logger.h:113: loglevel_str2num
node.c:489: node_log_level_set
common.c:261: do_generic_subcommand
segmentation fault

Thanks
Yuichi Bando

**Comment by vtolstov** [comment]
@mitake as for version 0.9.0_176_ged83bce this is not happening (so issue already solved).
please close.

**Comment by mitake** [comment]
thanks for checking
