### ISSUE TITLE
sheep should flush object cache to another nodes

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#81]
In the current object cache option, replica is not created until users issue sync request expressly.
Therefore, data may lost when the local HDD of sheep server fails.

Sheep should flush object cache to another nodes periodically.

**Comment by tmenjo** [comment]
I think this issue may be closed because object cache feature is removed from v1.0 or later.

(Though, in stable-0.9, it still remains...)

**Comment by mitake** [comment]
yes, let's close
