### ISSUE TITLE
qemu-img doesn't use correct nr_copies for taking snapshot

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#84]
As fixed in this commit: https://github.com/sheepdog/sheepdog/commit/fe3f8001e8fc9ecf21acb5220d67a2cc203b9ebe , qemu-img uses invalid copy number when it takes snapshot.

**Comment by vtolstov** [comment]
i don't see this issue under latest qemu, so i think that this issue can be closed

**Comment by mitake** [comment]
ok then let's close it
