### ISSUE TITLE
multiple snapshots can be created with a same tag

### ISSUE THREAD

**Issue by mitake** [sheepdog/sheepdog#93]
We found that we can create multiple snapshots with a same tag.
However, rollback is executed with the largest snapshot id (as far as I confirmed).
This behavior is right ?
We worry that it becomes the cause of the malfunction.

**Comment by vtolstov** [comment]
As i understand tags is like xattrs, so it can be identical.
Also as i understand only snapshot id (vdi id) is uniq, so why not remove ability to rollback from snapshot by tag name and also remove ability to provide tag name for snapshot?
If user wants he can add tags after snapshot created?

**Comment by mitake** [comment]
> remove ability to rollback from snapshot by tag name
seems good idea. Could you add this issue?

but,
> remove ability to provide tag name for snapshot?
it seems to be overkill.

> If user wants he can add tags after snapshot created?
It is difficult because of the basic structure of sheepdog.
